version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 143063372153.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=143063372153.dkr.ecr.us-east-2.amazonaws.com/braintask
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating Kubernetes deployment manifest...
      - sed -i 's|image:.*|image':' '$REPOSITORY_URI':'$IMAGE_TAG'|g' Kubernetes/deployment.yaml
      - echo Writing image definitions file...
      - printf '[{"name":"brain-task-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Build process completed successfully

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - scripts/**/*
    - Kubernetes/**/*